server:
  port: 3344
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wxroot/microservice-config.git
          username: wxroot@outlook.com
          password: openoa123
